version: '3'

services:
  kirby:
    image: richarvey/nginx-php-fpm:latest
    container_name: kirby-bootstrap-starter
    env_file:
      - .env
    environment:
      - SKIP_COMPOSER=1
      - PHP_MEM_LIMIT=1024
      - PHP_ERRORS_STDERR=1
      - WEBROOT=/var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "$MIX_HTTP_PORT:80"
